name: Lezard
favicon: null
layout_spectrum: 0.2914034000132233
typography_spectrum: 0.7230816290248185
title: Lezard - Build beautiful websites
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e2017b'
    - '#020305'
    - '#8d827e'
    - '#c7cc54'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
