name: kameleo
favicon: null
layout_spectrum: 0.2914034000132233
typography_spectrum: 0.7230816290248185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7071487086359411
  lightness: 0.7354022725485265
  saturation: 0.11274289945140481
  rhythmicContrast: 0.1556742328684777
purpose: []
